export const LIST_MENU = [
    {
        created_at: '2023-12-04T08:16:22.664Z',
        created_by: '1',
        created_name: 'System',
        updated_at: '2023-12-04T08:16:22.664Z',
        updated_by: null,
        updated_name: null,
        deleted_at: null,
        deleted_by: null,
        deleted_name: null,
        id: '435ad1cc-a65f-4d09-9ba1-6def046cccc3',
        level: 1,
        code: 'dashboard.main',
        create: 1,
        read: 1,
        update: 1,
        delete: 1,
        approve: 1,
        menu: {
            created_at: '2023-09-12T17:23:40.252Z',
            created_by: 'Fer',
            created_name: 'System',
            updated_at: '2023-12-05T04:29:53.185Z',
            updated_by: 'ddfcbb09-3bdf-4fce-800a-4fc3de201bf0',
            updated_name: 'Solehudin',
            deleted_at: null,
            deleted_by: null,
            deleted_name: null,
            id: '0ebb5d8d-8597-4728-8e95-7c70b66a8bbc',
            name: 'Home',
            key: 'dashboard.main',
            url: '/home',
            icon: 'home',
            parent_id: 'ROOT',
            environment: ['DEVELOPMENT', 'STAGING'],
            group_menu: 'DASHBOARD',
            order: 1,
            show: true,
        },
        title: 'DASHBOARD',
        menus: [
            {
                created_at: '2023-12-04T08:16:22.664Z',
                created_by: '1',
                created_name: 'System',
                updated_at: '2023-12-04T08:16:22.664Z',
                updated_by: null,
                updated_name: null,
                deleted_at: null,
                deleted_by: null,
                deleted_name: null,
                id: '435ad1cc-a65f-4d09-9ba1-6def046cccc3',
                level: 1,
                code: 'dashboard.main',
                create: 1,
                read: 1,
                update: 1,
                delete: 1,
                approve: 1,
                menu: {
                    created_at: '2023-09-12T17:23:40.252Z',
                    created_by: 'Fer',
                    created_name: 'System',
                    updated_at: '2023-12-05T04:29:53.185Z',
                    updated_by: 'ddfcbb09-3bdf-4fce-800a-4fc3de201bf0',
                    updated_name: 'Solehudin',
                    deleted_at: null,
                    deleted_by: null,
                    deleted_name: null,
                    id: '0ebb5d8d-8597-4728-8e95-7c70b66a8bbc',
                    name: 'Home',
                    key: 'dashboard.main',
                    url: '/home',
                    icon: 'home',
                    parent_id: 'ROOT',
                    environment: ['DEVELOPMENT', 'STAGING'],
                    group_menu: 'DASHBOARD',
                    order: 1,
                    show: true,
                },
                sub_menu: [],
            },
        ],
    },
];
